### ISSUE TITLE
Envelope simulation for rule testing

### ISSUE THREAD

**Issue by RyanFleck** [Xalgorithms/lib-rules-int-scala#12]
Passing *simulated envelopes* would remove the need for extra tables during testing.

Until *WHEN* is fully implemented, simulated envelopes are less important.

**Comment by karfai** [comment]
So... I'm only *luke-warm* about "document". The data that is addressed in that section is basically a document, rather than a table, that addresses most of the information in the invoice that **is not items**. To me "document" is too generic. "Heading" too is too generic.

I've thought about it *alot* though and I can't come up with a better name for the thing. I'm thinking I'll just go with "document" (my misgivings aside) because at least in that case, it represents "this is the document that was sent". This means that the rules author *will be able* to address the items in the document even though they're also available in the *tables* section. I'm not sure of the implications of that choice but I'll assume that, since *table:items* also exists, most rules authors will opt to use the data that in the more convenient *shape*.

**Comment by karfai** [comment]
Closing as no longer relevant. Some changes will be made in the v0.0.4 milestone that will made this irrelevant.
